#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PYTHONPATH="$PYTHONPATH:$THIS_DIR/python3/packages:$THIS_DIR/python3/testroots"

source $THIS_DIR/.venv/bin/activate

ipython -i $THIS_DIR/python3/console/startup.py
