#!/bin/bash

# ==============================================================================
# Description:
#
#     This script processes file trees of specific parent folders in the
# Automation directory and cleans the files of trailing whitespace.
#
# ==============================================================================

# Establish the base repository reference directory
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
AUTOMATION_DIR="$( dirname $( dirname $THIS_DIR ) )"

echo "THIS_DIR=$THIS_DIR"
echo "AUTOMATION_DIR=$AUTOMATION_DIR"

# Find and clean all the line endings of python files
if [ -d $AUTOMATION_DIR/python3/packages ]; then
    echo "cleaning packages directory..."
    find $AUTOMATION_DIR/python3/packages -name '*.py' | xargs --verbose sed -i 's/[[:space:]]*$//'
fi

if [ -d $AUTOMATION_DIR/python3/testroots ]; then
    echo "cleaning testroots directory..."
    find $AUTOMATION_DIR/python3/testroots -name '*.py' | xargs --verbose sed -i 's/[[:space:]]*$//'
fi
