#!/bin/bash

# ==============================================================================
# Description:
#
#     This script prints out the environment variables that have been set in
# the workspace environment.
#
# ==============================================================================

# Establish the base repository reference directory
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $THIS_DIR/../../_local/development.env

export AUTOMATION_DIR=$AUTOMATION_DIR
export REPOSITORY_DIRECTORY=$REPOSITORY_DIRECTORY
export DEVELOPER_MODE=$DEVELOPER_MODE
export PYTHONPATH=$PYTHONPATH

echo "=================== Workspace Environment ==================="
echo "      AUTOMATION_DIR: ${AUTOMATION_DIR}"
echo " REPOSITORY_DIRECTORY: ${REPOSITORY_DIRECTORY}"
echo "       DEVELOPER_MODE: ${DEVELOPER_MODE}"
echo "           PYTHONPATH: ${PYTHONPATH}"

python "$THIS_DIR/show-env.py"
